### ISSUE TITLE
Place chat messages each on their own line

### ISSUE THREAD

**Issue by FRC-Bunnyhug** [voc0der/NWNLogRotator#17]
Could the program be updated to place all chat messages on their own line instead of all on the same line? It would help with parsing all of my rotated logs in a terminal.

The logs look great when opened in a Web Browser, but I often parse all of them for historical reasons with a single command and having everything on one line makes it a bit messy.

**Comment by FRC-Bunnyhug** [comment]
For anyone else wishing this feature, I came up with a simple sed script:

```
$ for x in *.html ; do sed 's/<br \/>/<br \/>\
/g' ${x} > lined/${x} ; mv ${x} orig_backup/ ; done
```

Make the directories "lined" and "orig_backup" within your rotated logs folder first. This script replaces each "<br />" with "<br />[newline]" while making fixed version copies of each log file into the "lined/" directory and then moving the originals to "orig_backup".

**Comment by NetSamurai** [comment]
Thanks for adding that!

**Comment by voc0der** [comment]
I suppose I can look
